//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTODRIVERCUSTOMER
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string Sync { get; set; }
        public Nullable<long> DRIVERID { get; set; }
        public Nullable<long> AUTOID { get; set; }
        public Nullable<long> CUSTOMERID { get; set; }
        public Nullable<long> CUSTOMERPERSONID { get; set; }
    
        public virtual CUSTOMERPERSON CUSTOMERPERSON { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual AUTO AUTO { get; set; }
        public virtual DRIVER DRIVER { get; set; }
    }
}
