//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTE()
        {
            this.WEIGHTINGS = new HashSet<WEIGHTING>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public Nullable<int> DRIVERID { get; set; }
        public Nullable<int> CUSTOMERTYPEID { get; set; }
        public Nullable<int> CHECKPOINTID { get; set; }
        public Nullable<int> COMMODITYID { get; set; }
        public string AUTONUMBER { get; set; }
        public string CHECKNUMBER { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<long> TRANSPORTERID { get; set; }
        public Nullable<long> CUSTOMERPERSONID { get; set; }
        public Nullable<long> CLOSED { get; set; }
        public Nullable<long> RETURNED { get; set; }
        public string RETURNMESSAGE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string SystemGuid { get; set; }
        public string Sync { get; set; }
        public Nullable<int> endPoint { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> waybill { get; set; }
        public Nullable<bool> Reconciliation { get; set; }
        public Nullable<bool> Lock { get; set; }
        public string TrailerNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEIGHTING> WEIGHTINGS { get; set; }
    }
}
