//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stud.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudDBEntities : DbContext
    {
        public StudDBEntities()
            : base("name=StudDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTODRIVERCUSTOMER> AUTODRIVERCUSTOMERs { get; set; }
        public virtual DbSet<AUTO> AUTOS { get; set; }
        public virtual DbSet<CHECKPOINT> CHECKPOINTS { get; set; }
        public virtual DbSet<COMMODITy> COMMODITIES { get; set; }
        public virtual DbSet<CUSTOMERPERSON> CUSTOMERPERSONS { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<CUSTOMERTYPE> CUSTOMERTYPES { get; set; }
        public virtual DbSet<DRIVER> DRIVERS { get; set; }
        public virtual DbSet<NOTE> NOTES { get; set; }
        public virtual DbSet<ORGANIZATION> ORGANIZATIONS { get; set; }
        public virtual DbSet<SNAPSHOT> SNAPSHOTS { get; set; }
        public virtual DbSet<TRASPORTERAUTO> TRASPORTERAUTOS { get; set; }
        public virtual DbSet<TRASPORTER> TRASPORTERS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<WEIGHTING> WEIGHTINGs { get; set; }
    }
}
