//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stud.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudDBEntities : DbContext
    {
        public StudDBEntities()
            : base("name=StudDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTODRIVERCUSTOMER> AUTODRIVERCUSTOMER { get; set; }
        public virtual DbSet<AUTOS> AUTOS { get; set; }
        public virtual DbSet<CHECKPOINTS> CHECKPOINTS { get; set; }
        public virtual DbSet<COMMODITIES> COMMODITIES { get; set; }
        public virtual DbSet<CUSTOMERPERSONS> CUSTOMERPERSONS { get; set; }
        public virtual DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public virtual DbSet<CUSTOMERTYPES> CUSTOMERTYPES { get; set; }
        public virtual DbSet<DRIVERS> DRIVERS { get; set; }
        public virtual DbSet<NOTES> NOTES { get; set; }
        public virtual DbSet<ORGANIZATIONS> ORGANIZATIONS { get; set; }
        public virtual DbSet<SNAPSHOTS> SNAPSHOTS { get; set; }
        public virtual DbSet<TRASPORTERAUTOS> TRASPORTERAUTOS { get; set; }
        public virtual DbSet<TRASPORTERS> TRASPORTERS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<WEIGHTING> WEIGHTING { get; set; }
    }
}
