//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASPORTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRASPORTER()
        {
            this.NOTES = new HashSet<NOTE>();
            this.TRASPORTERAUTOS = new HashSet<TRASPORTERAUTO>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public string INFO { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string INN { get; set; }
        public string CEOPOSTION { get; set; }
        public string CEOFIO { get; set; }
        public string LEGALADDRESS { get; set; }
        public string Sync { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTE> NOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRASPORTERAUTO> TRASPORTERAUTOS { get; set; }
    }
}
