//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stud.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.NOTES = new HashSet<NOTE>();
        }
    
        public long ID { get; set; }
        public string Login { get; set; }
        public string PWD { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> ADMIN { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string POSITION { get; set; }
        public int EDITOR { get; set; }
        public string Sync { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTE> NOTES { get; set; }
    }
}
