//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studwebapimvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTODRIVERCUSTOMER
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string Sync { get; set; }
        public Nullable<int> DRIVERID { get; set; }
        public Nullable<int> AUTOID { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public Nullable<int> CUSTOMERPERSONID { get; set; }
    }
}
