//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studwebapimvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTODRIVERCUSTOMER
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string Sync { get; set; }
        public Nullable<long> DRIVERID { get; set; }
        public Nullable<long> AUTOID { get; set; }
        public Nullable<long> CUSTOMERID { get; set; }
        public Nullable<long> CUSTOMERPERSONID { get; set; }
    
        public virtual CUSTOMERPERSONS CUSTOMERPERSONS { get; set; }
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual AUTOS AUTOS { get; set; }
        public virtual DRIVERS DRIVERS { get; set; }
    }
}
