//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studwebapimvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseEntities : DbContext
    {
        public databaseEntities()
            : base("name=databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTODRIVERCUSTOMER> AUTODRIVERCUSTOMER { get; set; }
        public virtual DbSet<AUTOS> AUTOS { get; set; }
        public virtual DbSet<CHECKPOINTS> CHECKPOINTS { get; set; }
        public virtual DbSet<COMMODITIES> COMMODITIES { get; set; }
        public virtual DbSet<CUSTOMERPERSONS> CUSTOMERPERSONS { get; set; }
        public virtual DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public virtual DbSet<CUSTOMERTYPES> CUSTOMERTYPES { get; set; }
        public virtual DbSet<DRIVERS> DRIVERS { get; set; }
        public virtual DbSet<NOTES> NOTES { get; set; }
        public virtual DbSet<ORGANIZATIONS> ORGANIZATIONS { get; set; }
        public virtual DbSet<SNAPSHOTS> SNAPSHOTS { get; set; }
        public virtual DbSet<TRASPORTERAUTOS> TRASPORTERAUTOS { get; set; }
        public virtual DbSet<TRASPORTERS> TRASPORTERS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<WEIGHTING> WEIGHTING { get; set; }
    }
}
