//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studwebapimvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTES
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string AUTONUMBER { get; set; }
        public string CHECKNUMBER { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<int> CLOSED { get; set; }
        public Nullable<int> RETURNED { get; set; }
        public string RETURNMESSAGE { get; set; }
        public string SystemGuid { get; set; }
        public string Sync { get; set; }
        public Nullable<int> waybill { get; set; }
        public Nullable<bool> Reconciliation { get; set; }
        public Nullable<bool> Lock { get; set; }
        public string TrailerNumber { get; set; }
        public string Pile { get; set; }
        public Nullable<int> StorageId { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public Nullable<int> DRIVERID { get; set; }
        public int CUSTOMERTYPEID { get; set; }
        public Nullable<int> CHECKPOINTID { get; set; }
        public Nullable<int> COMMODITYID { get; set; }
        public Nullable<int> TRANSPORTERID { get; set; }
        public Nullable<int> CUSTOMERPERSONID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> endPoint { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
