//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studwebapimvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTES()
        {
            this.NOTES1 = new HashSet<NOTES>();
            this.SNAPSHOTS = new HashSet<SNAPSHOTS>();
            this.WEIGHTING = new HashSet<WEIGHTING>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string AUTONUMBER { get; set; }
        public string CHECKNUMBER { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<int> CLOSED { get; set; }
        public Nullable<int> RETURNED { get; set; }
        public string RETURNMESSAGE { get; set; }
        public string SystemGuid { get; set; }
        public string Sync { get; set; }
        public Nullable<int> waybill { get; set; }
        public Nullable<bool> Reconciliation { get; set; }
        public Nullable<bool> Lock { get; set; }
        public string TrailerNumber { get; set; }
        public string Pile { get; set; }
        public Nullable<long> StorageId { get; set; }
        public Nullable<long> CUSTOMERID { get; set; }
        public Nullable<long> DRIVERID { get; set; }
        public long CUSTOMERTYPEID { get; set; }
        public Nullable<long> CHECKPOINTID { get; set; }
        public Nullable<long> COMMODITYID { get; set; }
        public Nullable<long> TRANSPORTERID { get; set; }
        public Nullable<long> CUSTOMERPERSONID { get; set; }
        public Nullable<long> USERID { get; set; }
        public Nullable<long> endPoint { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual CHECKPOINTS CHECKPOINTS { get; set; }
        public virtual COMMODITIES COMMODITIES { get; set; }
        public virtual CUSTOMERPERSONS CUSTOMERPERSONS { get; set; }
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual CUSTOMERTYPES CUSTOMERTYPES { get; set; }
        public virtual DRIVERS DRIVERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTES> NOTES1 { get; set; }
        public virtual NOTES NOTES2 { get; set; }
        public virtual ORGANIZATIONS ORGANIZATIONS { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual TRASPORTERS TRASPORTERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SNAPSHOTS> SNAPSHOTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEIGHTING> WEIGHTING { get; set; }
    }
}
