//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studwebapimvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATIONS
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string INFO { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string LEGALADDRESS { get; set; }
        public string Sync { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> DefaultOrganizations { get; set; }
        public string SystemGuid { get; set; }
        public string WarehouseManager { get; set; }
    }
}
