//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studwebapimvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASPORTERAUTOS
    {
        public long TRANSPORTERID { get; set; }
        public long AUTOID { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string Sync { get; set; }
    
        public virtual AUTOS AUTOS { get; set; }
        public virtual TRASPORTERS TRASPORTERS { get; set; }
    }
}
